# -*- coding: utf-8 -*-
"""ml.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11rK5BULvK-ZjcxN0RAB82vD2aSt4T472
"""

# Import the required libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Sample dataset for demonstration
data = {
    'Age': [25, 30, 28, 35, 20, 22, 32, 40],
    'Gender': [1, 0, 1, 0, 1, 0, 1, 0],
    'Category': [0, 1, 1, 0, 1, 0, 0, 1],
    'Click': [1, 0, 1, 0, 1, 0, 1, 0]
}

df = pd.DataFrame(data)

# Split data into features and target
X = df[['Age', 'Gender', 'Category']]
y = df['Click']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Model accuracy:", accuracy)